AUTO_SUGGEST_URL = "https://search-books-main-5xruavjoyo7mq2fem4jwni4ace.ap-south-1.es.amazonaws.com/books_main/_search"
ADD_DATA_URL = "https://search-books-main-5xruavjoyo7mq2fem4jwni4ace.ap-south-1.es.amazonaws.com/books_main/_doc"
HEADERS = {
    'Authorization': 'Basic <AUTH>',
    'Content-Type': 'application/json'
}
INDEXING_URL = "https://search-books-main-5xruavjoyo7mq2fem4jwni4ace.ap-south-1.es.amazonaws.com/books_main/_doc"
MASTER_FILES_PATH = "/Users/vagishasharma/Documents/suggest-books/file_name_to_replace.csv"
FILE_NAME_TO_REPLACE = "file_name_to_replace"
EMPTY_STRING = " "
UNDERSCORE = "_"
BOOK_TITLE_WRAPPER = "book_title_wrapper"
BOOK_LINK = "book_image_src"
AUTHOR = "book_author"
STRIKETHROUGH = "strikethrough"
BOOK_TYPE= "book_type"
GENRE = "Book_by_Genre"
SOURCE = "_source"
QUERY = "query"
MATCH = "match"
HITS = "hits"
BY = "by"
MULTIMATCH = "multi_match"
CONTENT_TYPE = "Content-Type"
USERNAME = "username"
PASSWORD = "password"
EMAIL = "email"
FNAME = "fname"
LNAME = "lname"
SUCCESS = "success"
MESSAGE = "message"
